kodi_github_repo:

  repositories:
    - https://github.com/andrewleech/plugin.video.sbsondemand
    - https://github.com/andrewleech/script.module.pyopenssl
    - https://github.com/beenje/script.module.requests
    - https://github.com/andrewleech/skin.corona
    - https://github.com/andrewleech/plugin.video.netflixbmc
    - https://github.com/andrewleech/plugin.program.chrome.launcher.git
    - https://github.com/andrewleech/repository.alelec.git

  redis_server:
    host: localhost
    port: 6379
    db: 0

  debug_server:
    port: 45210